--Row 1
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM1',N'Mì ăn liền');
--Row 2
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM2',N'Nước giải khát & Nước suối');
--Row 3
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM3',N'Bia & Đồ uống có cồn');
--Row 4
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM4',N'Sữa & Sản phẩm từ sữa');
--Row 5
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM5',N'Bánh kẹo & Snack');
--Row 6
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM6',N'Kem & Thực phẩm đông lạnh');
--Row 7
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM7',N'Thực phẩm tươi sống');
--Row 8
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM8',N'Đồ ăn sẵn (Ready-to-eat)');
--Row 9
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM9',N'Gia vị & Đồ khô');
--Row 10
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM10',N'Hóa mỹ phẩm (Dầu gội, sữa tắm)');
--Row 11
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM11',N'Chăm sóc cá nhân (Bàn chải, kem đánh răng)');
--Row 12
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM12',N'Vệ sinh nhà cửa (Nước tẩy rửa)');
--Row 13
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM13',N'Đồ dùng gia đình thiết yếu');
--Row 14
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM14',N'Văn phòng phẩm cơ bản');
--Row 15
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM15',N'Thực phẩm cho bé');
--Row 16
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM16',N'Sản phẩm chăm sóc sức khỏe');
--Row 17
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM17',N'Thức ăn cho thú cưng');
--Row 18
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM18',N'Sơ mi & Áo thun cơ bản');
--Row 19
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM19',N'Gạo');
--Row 20
INSERT INTO DANHMUC_SANPHAM (MADANHMUC, TENDANHMUC) VALUES ('DM20',N'Dụng cụ ăn uống một lần');
